name = "Nesquate's Server Modpack"
author = "Nesquate"
version = "s2-2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86a244b461408909fdd8f3395274bd614ecf952ddfca422c6e167ee864391e07"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
