name = "Nesquate's Server Modpack"
author = "Nesquate"
version = "s1-6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "205628fe609b6a33fb8dac8b26cac398ae30b025faccfe86a179afefba3b1c9a"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
