name = "Nesquate's Server Modpack"
author = "Nesquate"
version = "s1-4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dfe5f51e9720871a4fab314c6f7c7b2c924880b39fcc0824c86604b46d9c97b1"

[versions]
fabric = "0.14.18"
minecraft = "1.19.4"
