name = "Nesquate's Server Modpack"
author = "Nesquate"
version = "s1-7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83a173cf85e07ffb2ec1f106ea9df53abdd659b4f98b0839e3a0a1a7feb3d434"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.2"]
