name = "Nesquate's Server Modpack"
author = "Nesquate"
version = "s2-6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "548a77d50008e3d0fb045b98f3837a78ecf3915ed059156cc83d59ada3a8d3a5"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.19.4"]
