name = "Nesquate's Server Modpack"
author = "Nesquate"
version = "s2-6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33494c8a4e84f80cbb5f1ad68dc4d7cc1b212baa7c41e81290ad3732478af237"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.19.4"]
